FROM php:8.2-apache

# Serve files from your static folder
RUN sed -i 's|/var/www/html|/var/www/html/src/frontend/static|' /etc/apache2/sites-available/000-default.conf

# Set default index file
RUN echo "DirectoryIndex main.html" >> /etc/apache2/apache2.conf

# Copy all files
WORKDIR /var/www/html
COPY . /var/www/html/

# Enable mod_rewrite
RUN a2enmod rewrite

EXPOSE 80
CMD ["apache2-foreground"]